/* timeline/icons.js — the three 16 px tool glyphs of the timeline's tool bar (harvested whole from BASINS
 * app/timeline-icons.js, 2026-10-02): generated by Gemini 3.8 Flash (high effort) through `agy` and checked by rendering
 * each at 64 px in Chromium (BASINS docs/plates/icons-2026-10-01/).  Single colour (currentColor), no text, no external
 * refs.  The editor puts them in EDIT, SELECT and SCRUB; each button keeps its word as its accessible name and hint. */

export const EDIT_ICON = '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 14l1.5-3.5 8-8 2 2-8 8z"/><line x1="3.5" y1="10.5" x2="5.5" y2="12.5"/><line x1="9.5" y1="4.5" x2="11.5" y2="6.5"/></svg>';

export const SELECT_ICON = '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="7" height="7" stroke-dasharray="1.5 1.5"/><rect x="6" y="6" width="8" height="8" stroke-dasharray="1.5 1.5"/></svg>';

export const SCRUB_ICON = '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="m5 5-3 3 3 3"/><line x1="8" y1="2" x2="8" y2="14" stroke-dasharray="1 1.5"/><path d="m11 5 3 3-3 3"/></svg>';

export const TIMELINE_ICONS = { edit: EDIT_ICON, select: SELECT_ICON, scrub: SCRUB_ICON };
