#!/usr/bin/env node
/* tokens-doc.mjs — docs/TOKENS.md is GENERATED from mir/tokens.json; never edit the .md by hand.
 *
 *   node tools/tokens-doc.mjs          rewrite docs/TOKENS.md
 *   node tools/tokens-doc.mjs --check  exit 1 if docs/TOKENS.md is not what the schema renders (tests/tokens.node.mjs does this too)
 *
 * The schema is the source: change a token's row in mir/tokens.json, then run this. */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const SCHEMA = path.join(ROOT, 'mir', 'tokens.json');
export const DOC = path.join(ROOT, 'docs', 'TOKENS.md');
const GROUPS = ['ink', 'accent', 'status', 'data', 'surface', 'face', 'relief', 'state', 'type', 'space', 'radius', 'motion', 'layout', 'z', 'info', 'gui', 'fx', 'runtime'];
const GROUP_LINE = {
  ink: 'The ink ladder. The 1.4 names stay the public names: an app re-points them per cell, and an alias would not follow.',
  accent: 'ACCENT A carries live signal and emphasis; ACCENT B carries relationships and time. Both are the user\'s.',
  status: 'Status inks.', data: 'Data inks. A skin does not restyle data.',
  surface: 'What a pane is made of. Three vocabularies name it today (`--glass-*`, `--m2-mat-*`, BASINS\' `--surface-*`); 1.5 keeps one, `--surface-*`, and reads the others as inputs.',
  face: 'What a control\'s face is made of, at rest and in each state.', relief: 'Shadows and bevels. Each one means one thing (docs/INTENT.md).',
  state: 'The 1.5 state tokens: one drawing per meaning.', type: 'Faces, sizes, tracking, weights.', space: 'Spacing and the 44 px law.',
  radius: 'Corners.', motion: 'Durations and easings (docs/MOTION-LAW.md).', layout: 'Geometry the layout reads. A skin that changes a size got something wrong.',
  z: 'Stacking.', info: 'INFORMATIONAL: words on the picture (docs/INFORMATIONAL.md).', gui: 'The GUI window (docs/GUI.md).', fx: 'The pointer glow and parallax (mir/fx/).', keyboard: 'The keyboard window (docs/KEYS.md).', 'shell-parts': 'The small shell parts: dialog, notice, busy mark, boot card, settings rows (docs/SHELL-PARTS.md).', folders: 'The project window (docs/FOLDERS.md).', runtime: 'Written per element at run time, by kit JS or by the app. Not a skin\'s.',
};
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');
const code = (s) => (s === undefined || s === null || s === '' ? '' : '`' + esc(s).replace(/`/g, "'") + '`');

export function render(schema) {
  const T = schema.tokens, L = [];
  const n = (f) => T.filter(f).length;
  L.push('# MIR · TOKENS', '');
  L.push('> **Generated** from `mir/tokens.json` by `node tools/tokens-doc.mjs`. Do not edit this file; edit the schema and re-run.', '> `tests/tokens.node.mjs` fails when this page and the schema disagree, and when the schema and the kit\'s sheets disagree.', '');
  const live = (t) => t.status !== 'proposed';
  L.push(`**${T.length} tokens:** ${n(live)} in the kit today — ${n((t) => t.declaredIn.length)} declared in its sheets, ${n((t) => live(t) && !t.declaredIn.length && t.readIn?.length)} read there and declared nowhere, ${n((t) => live(t) && !t.declaredIn.length && !t.readIn?.length)} written only by kit script — and ${n((t) => !live(t))} proposed for 1.5.`, '');
  L.push('| status | count |', '|---|---|');
  for (const s of ['stable', 'alias-of', 'deprecated', 'proposed']) L.push(`| ${s} | ${n((t) => t.status.split(':')[0] === s)} |`);
  L.push('', '## How to read a row', '');
  L.push('| field | meaning |', '|---|---|',
    '| **tier** | `primitive` a raw scale step · `semantic` what a thing is for (the names components read) · `component` one part\'s knob, read with a semantic fallback at the use site |',
    '| **type** | color · color-channels (`H S% L%` for `hsl(var(--x) / a)`) · angle · percentage · number · length · shadow · filter · image · duration · easing · font · keyword · outline (an `outline` shorthand) · border (a `border` shorthand) · font-shorthand (a whole `font`) |',
    '| **dark / light** | the value the kit gives it, per theme (light only where it differs). For a plugin token, the value in the plugin seat (`.mir-modwindow, .kwin-chiprail, .m2ghost`) |',
    '| **owner** | `kit` its sheets declare it · `plugin` only the modulation sheets do · `app-input` the kit reads it and the app writes it · `runtime` written per element by script |',
    '| **skin** | ✓ a skin may set it. Geometry, data, runtime and plugin tokens are not a skin\'s (the PORTED-WINDOW EXCEPTION: a host sets the plugin\'s accent hues, nothing else) |',
    '| **status** | `stable` · `alias-of:--x` the same value under a second name · `deprecated` going (dead or inert) · `proposed` a 1.5 name, not in the sheets yet; it reads its **fallback** (a 1.4 name) at the use site |',
    '| **intent** | the meaning it carries in docs/INTENT.md, if any |', '');
  L.push('Flags: **dead** declared and read by nothing · **inert** draws nothing (transparent lights) · **unread-in-kit** read by apps, not the kit · **read-by-js** read only by kit script · **js-written** kit script writes it too · **js-only** only kit script writes it · **no-writer** read, and nothing in the kit writes it · **parallel-pane:…** one of the three pane vocabularies.', '');
  for (const g of [...new Set([...GROUPS, ...T.map((t) => t.group)])]) {   // a group the list does not name yet is still drawn, after the named ones
    const rows = T.filter((t) => t.group === g);
    if (!rows.length) continue;
    L.push(`## ${g}`, '', GROUP_LINE[g] || '', '');
    L.push('| token | tier | type | dark | light | owner | skin | status | intent | note |', '|---|---|---|---|---|---|---|---|---|---|');
    for (const t of [...rows.filter((t) => t.status !== 'proposed'), ...rows.filter((t) => t.status === 'proposed')]) {
      const dark = t.status === 'proposed' ? (t.fallback ? `→ ${code('var(' + t.fallback + ')')}` : t.fallbackExpr ? `→ ${code(t.fallbackExpr)}` : '—') : code(t.default?.dark);
      const flags = t.flags?.length ? ' *[' + t.flags.join(', ') + ']*' : '';
      L.push(`| ${code(t.name)} | ${t.tier} | ${t.type} | ${dark} | ${code(t.default?.light)} | ${t.owner} | ${t.skin ? '✓' : ''} | ${esc(t.status)} | ${t.intent || ''} | ${esc(t.note)}${flags} |`);
    }
    L.push('');
  }
  L.push('## The three pane vocabularies', '');
  L.push('| vocabulary | where | tokens |', '|---|---|---|');
  for (const [k, where] of [['glass', 'kit `base.css`, `skin.css`'], ['m2-mat', 'plugin `modhost.css`, `modwindow.css`'], ['surface', 'BASINS `surface-material.css` today; the kit\'s 1.5 name (proposed)']])
    L.push(`| \`--${k === 'glass' ? 'glass-*' : k === 'm2-mat' ? 'm2-mat-*' : 'surface-*'}\` | ${where} | ${T.filter((t) => t.flags?.includes('parallel-pane:' + k)).map((t) => code(t.name)).join(' ')} |`);
  L.push('', '## Dead, inert, and written from script', '');
  L.push('| kind | tokens |', '|---|---|');
  for (const f of ['dead', 'inert', 'unread-in-kit', 'read-by-js', 'js-only', 'js-written', 'no-writer']) L.push(`| ${f} | ${T.filter((t) => t.flags?.includes(f)).map((t) => code(t.name) + (t.writtenBy ? ' (' + t.writtenBy.join(', ') + ')' : '')).join(' ') || '—'} |`);
  L.push('');
  return L.join('\n');
}

function main() {
  const schema = JSON.parse(fs.readFileSync(SCHEMA, 'utf8'));
  const md = render(schema);
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(DOC) ? fs.readFileSync(DOC, 'utf8') : '';
    if (have !== md) { console.log('docs/TOKENS.md is stale: run `node tools/tokens-doc.mjs`'); return 1; }
    console.log('docs/TOKENS.md is up to date'); return 0;
  }
  fs.writeFileSync(DOC, md);
  console.log(`docs/TOKENS.md written: ${schema.tokens.length} tokens`);
  return 0;
}
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) process.exit(main());
